{
 "title": "Netology-HW-Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU LoadAverage 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"} - node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "RAM Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"node-exporter:9100\", mode=\"idle\"}[5m]))*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\"} - node_filesystem_free_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\"}",
     "legendFormat": "Usage space"
    },
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\"}",
     "legendFormat": "Free space"
    }
   ]
  }
 ]
}